ABANDONMENT_LIMIT: 3
AFFINE_TRANSFORMATIONS_ENABLED: true
BATCH_SIZE: 128
COLONY_SIZE: 7
CONFIG_VERSION: config_version
CONTRAST_AUG_PROB: 0.75
CUTOUT_PROB: 0.8
DATASET: CIFAR10
DEPTH: 7
EMPLOYEE_ONLOOKER_RATIO: 0.43
ENABLE_WEIGHT_SAVING: false
EPOCHS: 5
FULL_TRAIN_EPOCHS: 50
HISTORY_FILES_SUBPATH: training_history/
INPUT_STEM: []
ITERATIONS_COUNT: 12
LR: 0.001
MOMENTUM_EPOCHS: 0
OPERATIONS:
  reference_space:
    avg_pool3x3: !Operation {op: AveragePooling2D, padding: same, pool_size: !!python/tuple [
        3, 3], strides: !!python/tuple [1, 1]}
    batch_norm: !Operation {op: BatchNormalization}
    conv3x3_16: !Operation {activation: relu, filters: 16, kernel_size: !!python/tuple [
        3, 3], op: Conv2D}
    dropout: !Operation {op: Dropout, rate: 0.15}
    identity: !Operation {op: Activation}
    max_pool3x3: !Operation {op: MaxPooling2D, padding: same, pool_size: !!python/tuple [
        3, 3], strides: !!python/tuple [1, 1]}
    sep3x3_128: !Operation {activation: relu, filters: 128, kernel_size: !!python/tuple [
        3, 3], op: SeparableConv2D, padding: same}
    sep3x3_32: !Operation {activation: relu, filters: 32, kernel_size: !!python/tuple [
        3, 3], op: SeparableConv2D, padding: same}
    sep3x3_64: !Operation {activation: relu, filters: 64, kernel_size: !!python/tuple [
        3, 3], op: SeparableConv2D, padding: same}
    sep5x5_128: !Operation {activation: relu, filters: 128, kernel_size: !!python/tuple [
        5, 5], op: SeparableConv2D, padding: same}
    sep5x5_32: !Operation {activation: relu, filters: 32, kernel_size: !!python/tuple [
        5, 5], op: SeparableConv2D, padding: same}
    sep5x5_64: !Operation {activation: relu, filters: 64, kernel_size: !!python/tuple [
        5, 5], op: SeparableConv2D, padding: same}
  search_space:
    avg_pool3x3: !Operation {op: AveragePooling2D, padding: same, pool_size: !!python/tuple [
        3, 3], strides: !!python/tuple [1, 1]}
    dropout: !Operation {op: Dropout, rate: 0.15}
    identity: !Operation {op: Activation}
    max_pool3x3: !Operation {op: MaxPooling2D, padding: same, pool_size: !!python/tuple [
        3, 3], strides: !!python/tuple [1, 1]}
    sep3x3_128: !Operation {activation: relu, filters: 128, kernel_size: !!python/tuple [
        3, 3], op: SeparableConv2D, padding: same}
    sep3x3_32: !Operation {activation: relu, filters: 32, kernel_size: !!python/tuple [
        3, 3], op: SeparableConv2D, padding: same}
    sep3x3_64: !Operation {activation: relu, filters: 64, kernel_size: !!python/tuple [
        3, 3], op: SeparableConv2D, padding: same}
    sep5x5_128: !Operation {activation: relu, filters: 128, kernel_size: !!python/tuple [
        5, 5], op: SeparableConv2D, padding: same}
    sep5x5_32: !Operation {activation: relu, filters: 32, kernel_size: !!python/tuple [
        5, 5], op: SeparableConv2D, padding: same}
    sep5x5_64: !Operation {activation: relu, filters: 64, kernel_size: !!python/tuple [
        5, 5], op: SeparableConv2D, padding: same}
OPTIMIZATION_OBJECTIVE: NAS
OPTIMIZER: Adam
OUTPUT_STEM:
- !Operation {op: Flatten}
- !Operation {op: Dropout, rate: 0.15}
- !Operation {activation: relu, op: Dense, units: 1024}
- !Operation {op: Dropout, rate: 0.15}
- !Operation {activation: relu, op: Dense, units: 512}
RESIDUAL_BLOCKS_RATE: 0.15
RESULTS_BASE_PATH: ../res/archived results/
RESULTS_SAVE_FREQUENCY: 1
RESUME_FROM_RESULTS_FILE: false
SATURATION_AUG_PROB: 0.75
TERMINATION_DIMINISHING_FACTOR: 0.25
TERMINATION_THRESHOLD_FACTOR: 0.0
WEIGHT_FILES_SUBPATH: weights/
