# Current Version
CONFIG_VERSION: default_sc_enabled

# Artificial Bee Colony Parameters
ABANDONMENT_LIMIT: 3
COLONY_SIZE: 5
EMPLOYEE_ONLOOKER_RATIO: 0.4
SCOUTS_COUNT: 2
ITERATIONS_COUNT: 15

# File-Handler Parameters
RESULTS_SAVE_FREQUENCY: 1
RESULTS_FILE_NAME: results.csv
RESULTS_FILE_PATH: /content/gdrive/MyDrive/PhD/HiveNAS/ResEnabled/
LOG_FILES_SUBPATH: logs/
ENABLE_WEIGHT_SAVING: False
WEIGHT_FILES_SUBPATH: weights/
RESUME_FROM_RESULTS_FILE: True

# NAS Search Space Parameters
DEPTH: 4     # Excluding input layer + output layer + stems
RESIDUAL_BLOCKS_RATE: 0.15    # skip-connections' occurence probability
OPERATIONS:
    sep3x3_64: !Operation {op: SeparableConv2D, filters: 64, kernel_size: !!python/tuple [3,3], activation: relu, padding: same}
    sep5x5_64: !Operation {op: SeparableConv2D , filters: 64 , kernel_size: !!python/tuple [5,5], activation: relu , padding: same}
    sep3x3_32: !Operation {op: SeparableConv2D , filters: 32 , kernel_size: !!python/tuple [3,3] , activation: relu , padding: same}
    sep5x5_32: !Operation {op: SeparableConv2D , filters: 32 , kernel_size: !!python/tuple [5,5] , activation: relu , padding: same}
    sep3x3_16: !Operation {op: SeparableConv2D , filters: 16 , kernel_size: !!python/tuple [3,3] , activation: relu , padding: same}
    sep5x5_16: !Operation {op: SeparableConv2D , filters: 16 , kernel_size: !!python/tuple [5,5] , activation: relu , padding: same}
    sep_dil_1x1_8: !Operation {op: SeparableConv2D , filters: 8 , kernel_size: !!python/tuple [1,1] , activation: relu , padding: same, dilation_rate: 2}
    max_pool3x3: !Operation {op: MaxPooling2D , pool_size: !!python/tuple [3,3], strides: !!python/tuple [1,1], padding: same}
    avg_pool3x3: !Operation {op: AveragePooling2D , pool_size: !!python/tuple [3,3], strides: !!python/tuple [1,1], padding: same}
    batch_norm: !Operation {op: BatchNormalization}
    dropout: !Operation {op: Dropout , rate: 0.2}

# NAS Evaluation Strategy configuration

DATASET: CIFAR10   # Specify the data loader in NASEval init
OUTPUT_STEM:
    - !Operation
        op: Flatten
    - !Operation
        op: Dropout
        rate: 0.25
    - !Operation
        op: Dense
        units: 1024
        activation: relu
    - !Operation
        op: Dropout
        rate: 0.25
    - !Operation
        op: Dense
        units: 512
        activation: relu

INPUT_STEM:
    - !Operation
        op: Conv2D
        filters: 32
        kernel_size: !!python/tuple [3,3]
    - !Operation
        op: BatchNormalization
    - !Operation
        op: ReLU

EPOCHS: 5       # static epochs number for non-momentum variations
FULL_TRAIN_EPOCHS: 100
LR: 0.001
BATCH_SIZE: 64
OPTIMIZER: Adam

# Dataset Augmentation Parameters
AFFINE_TRANSFORMATIONS_ENABLED: True
CUTOUT_PROB: 0
SATURATION_AUG_PROB: 0.75
CONTRAST_AUG_PROB: 0.75


